version: "3"
services:
  postgresql-server:
    image: postgres
    volumes:
        - ./docker:/docker-entrypoint-initdb.d
    container_name: dev-challenge-database
    hostname: postgres-server
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_MULTIPLE_DATABASES="dev-challenge-db-dev","dev-challenge-db-test"
      - POSTGRES_PASSWORD=ad3225ca3430a25e1e2a8bb6d97efa79
      - POSTGRES_USER=lucid
